name: pythonCI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pylint
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint encoder/encoder/encode.py
    - name: Build package
      run: python -m build
    - name: Get version from file
      run: |
        VER=$(cat version)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Install locally to test
      run: python -m pip install ./dist/encodepacakge-${{ env.VERSION }}.tar.gz
    # - name: Run unit test
    #   run: python ./test/test_encode.py
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: pypi-AgEIcHlwaS5vcmcCJGU2YWM1NTdiLWU0MTAtNGNhMS1hMmFhLTJhNmQwODg1OTczOQACKlszLCJiM2E1MWM4OC01ZWRlLTRlMmEtYTEyYS0xMmNiZTdjMDQ2ZGUiXQAABiDx0j92chntwfAHEO-bQDhOgpqYwpVIDEpNxb7UFKCMvA

      
      